c_compiler_version:        # [linux or osx]
  - 14.3.0                 # [linux]
cxx_compiler_version:      # [linux or osx]
  - 14.3.0                 # [linux]
fortran_compiler_version:  # [linux or osx]
  - 14.3.0                 # [linux]
  - 11.3.0                 # [osx]
