{% set name = "gdb" %}
{% set version = "14.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url:
    - https://ftp.gnu.org/gnu/gdb/gdb-{{ version }}.tar.xz
    - https://mirrors.ocf.berkeley.edu/gnu/gdb/gdb-{{ version }}.tar.xz
  sha256: 2d4dd8061d8ded12b6c63f55e45344881e8226105f4d2a9b234040efa5ce7772
  patches:

build:
  number: 0
  # GDB 14.2 uses _PyOS_ReadlineTState (removed in Python 3.13 C API)
  skip: true  # [not linux or py<310 or py>312]
  script_env:
    - TMPDIR

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - make >=3.82
    # python .../python-config.py --ldflags report -lcrypt for 3.9 and
    # 3.10 which is subsequently used during configure and later
    # during make. libcrypt-devel has the libcrypt.so itself
    - {{ cdt('libxcrypt-devel') }}  # [py<311]
  host:
    - python
    # match texinfo's pl526 build (avoid makeinfo Perl XS ABI mismatch)
    - perl =5.26.*
    - ncurses {{ ncurses }}
    - texinfo 6.5
    - xz {{ xz }}
    - zlib {{ zlib }}
    - readline {{ readline }}
    - libiconv {{ libiconv }}  # [osx]
    - libexpat {{ libexpat }}
    - gmp {{ gmp }}
    - mpfr {{ mpfr }}
  run:
    - python
    - ncurses
    - xz
    - zlib
    - six
    - libiconv  # [osx]
    - libexpat
    - pygments

test:
  commands:
    - $PREFIX/bin/gdb --version
    - $PREFIX/bin/gdb -q -ex "show host-charset" --batch
  requires:
    - {{ compiler('c') }}

about:
  home: https://www.gnu.org/software/gdb/
  license: GPL-3.0-only
  license_family: GPL
  license_file: gdb/COPYING
  summary: GDB, the GNU Project debugger, allows you to see what is going on inside another program while it executes -- or what another program was doing at the moment it crashed.
  description: |
    GDB, the GNU Project debugger, allows you to see what is going on `inside'
    another program while it executes -- or what another program was doing at
    the moment it crashed.
    The program being debugged can be written in Ada, C, C++, Objective-C,
    Pascal (and many other languages). Those programs might be executing on the
    same machine as GDB (native) or on another machine (remote).
    GDB can run on most popular UNIX and Microsoft Windows variants.
  doc_url: https://sourceware.org/gdb/current/onlinedocs/gdb/
  dev_url: https://sourceware.org/git/binutils-gdb.git

extra:
  recipe-maintainers:
    - gqmelo
    - marcelotrevisani
    - phil-blain
    - matthiasdiener
