{% set build_num = 0 %}

# You can use this to allow investigating errors in more recent glibcs than
# you have RPMs to make the sysroot packages from.
{% set hack_sysroot_ver = False %}
# {% set hack_sysroot_ver = '2.17' %}

package:
  name: gcc-compiler
  version: {{ gcc_version }}

source:
  path: .

build:
  merge_build_host: False
  # defined in conda_build_config.yaml so that we can keep it associated with a particular GCC version number
  number: {{ build_num | default(0) }}
  # The CentOS7 system libraries should be used for everything here.
  # We do not have CDT packages yet, nor compilers that would use them!
  missing_dso_whitelist:
    - "*"
  ignore_run_exports:
    - zlib
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # instead we install this dependency during build
    - llvm-tools  # [osx]
    - make
    - bash        # [not (ppc64le or s390x or aarch64)]
    - autoconf 
    - automake
    - libtool
    - bison
    - flex
    - sed
    - patch
    - gawk
    - m4
    - help2man
    - texinfo
    - git
    - python
  host:
    - python
outputs:
  - name: gdb-pretty-printer
    version: {{ gcc_version }}
    script: install_scripts/install-gdb-pretty-printer.sh
    build:
      number: {{ build_num }}
    requirements:
      host:
        - python
      run:
        - python
        - gdb >={{ gdb_version }}
        - libstdcxx-ng >={{ gcc_version }}
    about:
      summary: GNU Compiler Collection Python Pretty Printers
      home: https://gcc.gnu.org/
      license: GPL-3.0-only WITH GCC-exception-3.1
  - name: gdb
    target: {{ target_platform }}
    version: {{ gdb_version }}
    script: install_scripts/install-gdb.sh
    build:
      number: {{ build_num }}
      missing_dso_whitelist:
        - /lib64/*  # [linux]
      ignore_run_exports:
        - zlib
    requirements:
      host:
        - python
      run:
        - libstdxx-ng
        - python
        - ncurses
        - six
        - zlib
        - xz
        - pygments

    test:
      commands:
        - gdb --version
    about:
      summary: The GNU Project Debugger
      home: https://www.gnu.org/software/gdb/
      license: GPL

# make the linter happy
about:
  summary: GNU Compiler Collection
  home: https://gcc.gnu.org/
  license: GPL-3.0-only WITH GCC-exception-3.1
  license_file:
    - gcc/COPYING
    - gcc/COPYING.lib
    - gcc/COPYING.RUNTIME
    - gcc/COPYING3
    - COPYING3.lib

extra:
  recipe-maintainers:
    - katietz
