travis:
  secure:
    BINSTAR_TOKEN: b1M4saUmnVWVf+Hm4eiqU33sXv05ssFbatH+/wiFqK/brbQyh8uVr3MN1Wssmy5IWs73P5m12l+Fgqf/ONEsKxveiqDvQoXm6FTNA11Un7i5rt7AhJHBtYK+Zv7W69qP6v80vf6iUo2vkG9dTJmxBFVLRVE51AhrlXLgpK0NHHAyyxs/7fw7v0CPKQEo8zzG5LpVhN+QIdU4of+pqKkOBUtqxvlYDxF5n02zNbQMQF/OG1Pd43YtApal6zbxxqTI3v+rTpDV1vYRe7mPSKUfFFiJViGpIAgiVYiBZDMI2SFoSkvNIn3Lq9XkCwrkNI9DkruzMJz40gUFmIDmJI5EQZeG/OW8QI7ghlWdJ+Mh7wctuoJbpwOHZGzaA0kVX8Ttd7lC4sSE5C+gMPx+XGTkbMf3/KF+2C1cpZxYgi7/RA3QlfpyVvcc2uctHqWS4dy0RmiKmYuGxBPS289ioWe+I+eXMsgAcGLoUxij/hLLNrDRLatQUvFr8g9Mx3n0EqRx9D6fTAbODg2d3J4xoYB41bmL6bawsy3AJoyzUowK0elgRmOPWOeg9fEgLNnDTKULkqfnCHUri0UuYCLCo5Ch+6LDK9CxUMf0bibEfLOB4DvAOyZZ0c09CZXY+2eNsN6g/ujcIcGIXLgU14oFwduoN2qXXK2Y/3dIBP8nFALLoXo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
