provider:
  osx: travis
  linux_ppc64le: default
conda_forge_output_validation: true
travis:
  osx_image: xcode9.4
os_version:
  linux_64: cos7
github:
  branch_name: main
  tooling_branch_name: main
