travis:
  secure:
    BINSTAR_TOKEN: QY80lXQxwVFf8xtTHbW73VlXxGWYXgetCacoWJB5TnIsUDpTI3Vctmi1S7K8vq2EUGXbN1o4IvdgQ48I+6DCPRzwtRMpWncjtKJKx8EOYeu4OM4/C9v6d4XuNJKGBO+zpV23ysO2SoLPx8qUcNnOXjWsOvSPuud2KUieW5Q9aza8Vy8GzQ5rceaBejgyVIKUlnwP9StCsPe5l9b3F8WwFT7xhBow8P/vvH9IfHSbVVM7jvjPEs4vts/HDCY0i7wqaVpio1gtzI8j5wCXEwQ6fS08R85YjDvBdykBKukEDMQk/8p/BPfa8Lntu7lBNoWH6NFSH4SPOZDkrEPFu4euycSdQVJXW5b9OZtAV7S0a2/WE6NtMrkOPKap9U+PlV6uLOVHhIxMu/nvru4+M2zoYfKdjIGpPywXDZMj4oq0tVXtgQ6DZSx083VDdx66Pz7may0MShOnOly/wMfzby1wZKel9MC0cDkKwT4FqQWnuhkdAAcb33EKQhpRdd/WWOps5fiSk4YPwftyTkJ3VZdeoZeKxJeIVsSu1O5t3xEUV/zEEyG7O7vJkxzXHWPQutzq294bLuS+BA9CiXQd9ILo+zKWFMexvT2z7Uy8ft7Unt3LOZdM5ODnQt9MVTWNHGFeU+XUXPH2iXd90k0qV6e2S1DFSsptTNiJtaRHZPO0Hsk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
